# https://www.elastic.co/guide/en/filebeat/reference/current/docker.html
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      # securityContext:
      #   runAsUser: 1000
      #   fsGroup: 1000
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.2
        # args: ["-c", "/etc/filebeat/filebeat.yml", "-e"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu:    100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml
        - name: containers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      #     type: DirectoryOrCreate
